version: '3'
services:
  flask:
    image: myimage
    build: ./app
    ports:
      - "8080:8080"
    volumes:
      - './app:/app'
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "inventory-app"
    command: ["python3", "main.py"]
    container_name: inventory-app
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "inventory-app"
    container_name: inventory-db